<?php

use Illuminate\Database\Seeder;

class OlinLinkXCompanyTableSeeder extends Illuminate\Database\Seeder {
	
	public function run(){
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>1,
			'company_id'=>1
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>2,
			'company_id'=>1
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>3,
			'company_id'=>1
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>1,
			'company_id'=>2
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>2,
			'company_id'=>2
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>3,
			'company_id'=>2
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>1,
			'company_id'=>3
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>2,
			'company_id'=>3
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>3,
			'company_id'=>3
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>1,
			'company_id'=>4
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>2,
			'company_id'=>4
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>3,
			'company_id'=>4
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>1,
			'company_id'=>5
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>2,
			'company_id'=>5
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>3,
			'company_id'=>5
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>1,
			'company_id'=>6
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>2,
			'company_id'=>6
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>3,
			'company_id'=>6
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>1,
			'company_id'=>7
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>2,
			'company_id'=>7
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>3,
			'company_id'=>7
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>1,
			'company_id'=>8
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>2,
			'company_id'=>8
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>3,
			'company_id'=>8
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>1,
			'company_id'=>9
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>2,
			'company_id'=>9
			)
		);
		\DB::table('oli_link_x_company')->insert(array(
			'link_id'=>3,
			'company_id'=>9
			)
		);
	}
}
